In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_excel("C:/Users/kusha/OneDrive/Desktop/Capstone Project/Capstone Project 2/retail_sales_dataset.xlsx")
print(df)

     Order_ID        Date Product_ID Product_Name     Category Region  \
0    ORD00000  2023-04-13    CLO_535        Shirt     Clothing  South
1    ORD00001  2023-05-02    FUR_566        Chair    Furniture   East
2    ORD00002  2023-06-01    CLO_230        Jeans     Clothing   East
3    ORD00003  2023-10-04    FUR_260        Table    Furniture  South
4    ORD00004  2023-06-19    FUR_575         Sofa    Furniture  North
..        ...         ...        ...          ...          ...    ...
995  ORD00995  2023-03-11    CLO_265        Shoes     Clothing   West
996  ORD00996  2023-12-15    CLO_683        Shirt     Clothing  South
997  ORD00997  2023-06-15    FUR_473        Table    Furniture  North
998  ORD00998  2023-11-06    ELE_457       Laptop  Electronics   West
999  ORD00999  2023-11-11    ELE_936       Laptop  Electronics  South

            City Customer_ID  Gender  Age  Units_Sold  Unit_Price  Discount  \
0        Chennai    CUST1860  Female   32           8        3872        20
1    Bhubaneswar    CUST5426  Female   28           8        3544        15
2          Patna    CUST2685  Female   19           8        2533         5
3        Chennai    CUST5555    Male   39           9         574         0
4          Delhi    CUST3747  Female   33           3        1999        15
..           ...         ...     ...  ...         ...         ...       ...
995         Pune    CUST3689  Female   39           4        3506        10
996    Hyderabad    CUST9240  Female   50           6        2280         5
997      Lucknow    CUST8645  Female   48           2         186        15
998         Pune    CUST1162  Female   51           2        2497         0
999      Chennai    CUST4446  Female   45           5        2890        10

      Revenue      Cost   Profit
0    24780.80  19305.61  5475.19
1    24099.20  18805.44  5293.76
2    19250.80  12600.56  6650.24
3     5166.00   4047.85  1118.15
4     5097.45   3844.86  1252.59
..        ...       ...      ...
995  12621.60  10011.10  2610.50
996  12996.00   7931.63  5064.37
997    316.20    205.22   110.98
998   4994.00   3995.60   998.40
999  13005.00  11034.17  1970.83

[1000 rows x 16 columns]

In [3]:
df.isnull().sum()

Order_ID        0
Date            0
Product_ID      0
Product_Name    0
Category        0
Region          0
City            0
Customer_ID     0
Gender          0
Age             0
Units_Sold      0
Unit_Price      0
Discount        0
Revenue         0
Cost            0
Profit          0
dtype: int64

In [5]:
df.dropna(inplace=True)
df

,Order_ID,Date,Product_ID,Product_Name,Category,Region,City,Customer_ID,Gender,Age,Units_Sold,Unit_Price,Discount,Revenue,Cost,Profit
0,ORD00000,2023-04-13,CLO_535,Shirt,Clothing,South,Chennai,CUST1860,Female,32,8,3872,20,24780.80,19305.61,5475.19
1,ORD00001,2023-05-02,FUR_566,Chair,Furniture,East,Bhubaneswar,CUST5426,Female,28,8,3544,15,24099.20,18805.44,5293.76
2,ORD00002,2023-06-01,CLO_230,Jeans,Clothing,East,Patna,CUST2685,Female,19,8,2533,5,19250.80,12600.56,6650.24
3,ORD00003,2023-10-04,FUR_260,Table,Furniture,South,Chennai,CUST5555,Male,39,9,574,0,5166.00,4047.85,1118.15
4,ORD00004,2023-06-19,FUR_575,Sofa,Furniture,North,Delhi,CUST3747,Female,33,3,1999,15,5097.45,3844.86,1252.59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,ORD00995,2023-03-11,CLO_265,Shoes,Clothing,West,Pune,CUST3689,Female,39,4,3506,10,12621.60,10011.10,2610.50
996,ORD00996,2023-12-15,CLO_683,Shirt,Clothing,South,Hyderabad,CUST9240,Female,50,6,2280,5,12996.00,7931.63,5064.37
997,ORD00997,2023-06-15,FUR_473,Table,Furniture,North,Lucknow,CUST8645,Female,48,2,186,15,316.20,205.22,110.98
998,ORD00998,2023-11-06,ELE_457,Laptop,Electronics,West,Pune,CUST1162,Female,51,2,2497,0,4994.00,3995.60,998.40
999,ORD00999,2023-11-11,ELE_936,Laptop,Electronics,South,Chennai,CUST4446,Female,45,5,2890,10,13005.00,11034.17,1970.83

In [6]:
df.isnull()

,Order_ID,Date,Product_ID,Product_Name,Category,Region,City,Customer_ID,Gender,Age,Units_Sold,Unit_Price,Discount,Revenue,Cost,Profit
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [8]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [11]:
df.drop_duplicates

<bound method DataFrame.drop_duplicates of      Order_ID        Date Product_ID Product_Name     Category Region  \
0    ORD00000  2023-04-13    CLO_535        Shirt     Clothing  South
1    ORD00001  2023-05-02    FUR_566        Chair    Furniture   East
2    ORD00002  2023-06-01    CLO_230        Jeans     Clothing   East
3    ORD00003  2023-10-04    FUR_260        Table    Furniture  South
4    ORD00004  2023-06-19    FUR_575         Sofa    Furniture  North
..        ...         ...        ...          ...          ...    ...
995  ORD00995  2023-03-11    CLO_265        Shoes     Clothing   West
996  ORD00996  2023-12-15    CLO_683        Shirt     Clothing  South
997  ORD00997  2023-06-15    FUR_473        Table    Furniture  North
998  ORD00998  2023-11-06    ELE_457       Laptop  Electronics   West
999  ORD00999  2023-11-11    ELE_936       Laptop  Electronics  South

            City Customer_ID  Gender  Age  Units_Sold  Unit_Price  Discount  \
0        Chennai    CUST1860  Female   32           8        3872        20
1    Bhubaneswar    CUST5426  Female   28           8        3544        15
2          Patna    CUST2685  Female   19           8        2533         5
3        Chennai    CUST5555    Male   39           9         574         0
4          Delhi    CUST3747  Female   33           3        1999        15
..           ...         ...     ...  ...         ...         ...       ...
995         Pune    CUST3689  Female   39           4        3506        10
996    Hyderabad    CUST9240  Female   50           6        2280         5
997      Lucknow    CUST8645  Female   48           2         186        15
998         Pune    CUST1162  Female   51           2        2497         0
999      Chennai    CUST4446  Female   45           5        2890        10

      Revenue      Cost   Profit
0    24780.80  19305.61  5475.19
1    24099.20  18805.44  5293.76
2    19250.80  12600.56  6650.24
3     5166.00   4047.85  1118.15
4     5097.45   3844.86  1252.59
..        ...       ...      ...
995  12621.60  10011.10  2610.50
996  12996.00   7931.63  5064.37
997    316.20    205.22   110.98
998   4994.00   3995.60   998.40
999  13005.00  11034.17  1970.83

[1000 rows x 16 columns]>

In [10]:
df

,Order_ID,Date,Product_ID,Product_Name,Category,Region,City,Customer_ID,Gender,Age,Units_Sold,Unit_Price,Discount,Revenue,Cost,Profit
0,ORD00000,2023-04-13,CLO_535,Shirt,Clothing,South,Chennai,CUST1860,Female,32,8,3872,20,24780.80,19305.61,5475.19
1,ORD00001,2023-05-02,FUR_566,Chair,Furniture,East,Bhubaneswar,CUST5426,Female,28,8,3544,15,24099.20,18805.44,5293.76
2,ORD00002,2023-06-01,CLO_230,Jeans,Clothing,East,Patna,CUST2685,Female,19,8,2533,5,19250.80,12600.56,6650.24
3,ORD00003,2023-10-04,FUR_260,Table,Furniture,South,Chennai,CUST5555,Male,39,9,574,0,5166.00,4047.85,1118.15
4,ORD00004,2023-06-19,FUR_575,Sofa,Furniture,North,Delhi,CUST3747,Female,33,3,1999,15,5097.45,3844.86,1252.59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,ORD00995,2023-03-11,CLO_265,Shoes,Clothing,West,Pune,CUST3689,Female,39,4,3506,10,12621.60,10011.10,2610.50
996,ORD00996,2023-12-15,CLO_683,Shirt,Clothing,South,Hyderabad,CUST9240,Female,50,6,2280,5,12996.00,7931.63,5064.37
997,ORD00997,2023-06-15,FUR_473,Table,Furniture,North,Lucknow,CUST8645,Female,48,2,186,15,316.20,205.22,110.98
998,ORD00998,2023-11-06,ELE_457,Laptop,Electronics,West,Pune,CUST1162,Female,51,2,2497,0,4994.00,3995.60,998.40
999,ORD00999,2023-11-11,ELE_936,Laptop,Electronics,South,Chennai,CUST4446,Female,45,5,2890,10,13005.00,11034.17,1970.83

In [13]:
df.rename(columns={'Revenue':'Earnings'},inplace = True)
df

,Order_ID,Date,Product_ID,Product_Name,Category,Region,City,Customer_ID,Gender,Age,Units_Sold,Unit_Price,Discount,Earnings,Cost,Profit
0,ORD00000,2023-04-13,CLO_535,Shirt,Clothing,South,Chennai,CUST1860,Female,32,8,3872,20,24780.80,19305.61,5475.19
1,ORD00001,2023-05-02,FUR_566,Chair,Furniture,East,Bhubaneswar,CUST5426,Female,28,8,3544,15,24099.20,18805.44,5293.76
2,ORD00002,2023-06-01,CLO_230,Jeans,Clothing,East,Patna,CUST2685,Female,19,8,2533,5,19250.80,12600.56,6650.24
3,ORD00003,2023-10-04,FUR_260,Table,Furniture,South,Chennai,CUST5555,Male,39,9,574,0,5166.00,4047.85,1118.15
4,ORD00004,2023-06-19,FUR_575,Sofa,Furniture,North,Delhi,CUST3747,Female,33,3,1999,15,5097.45,3844.86,1252.59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,ORD00995,2023-03-11,CLO_265,Shoes,Clothing,West,Pune,CUST3689,Female,39,4,3506,10,12621.60,10011.10,2610.50
996,ORD00996,2023-12-15,CLO_683,Shirt,Clothing,South,Hyderabad,CUST9240,Female,50,6,2280,5,12996.00,7931.63,5064.37
997,ORD00997,2023-06-15,FUR_473,Table,Furniture,North,Lucknow,CUST8645,Female,48,2,186,15,316.20,205.22,110.98
998,ORD00998,2023-11-06,ELE_457,Laptop,Electronics,West,Pune,CUST1162,Female,51,2,2497,0,4994.00,3995.60,998.40
999,ORD00999,2023-11-11,ELE_936,Laptop,Electronics,South,Chennai,CUST4446,Female,45,5,2890,10,13005.00,11034.17,1970.83